services:
  db:
    build:
      context: ../database/
      dockerfile: db.Dockerfile
    image: electronmaildb
    container_name: em_db
    volumes:
      - em-db-data:/opt/oracle/oradata

    environment:
      ORACLE_PWD: password #tymczasowe has≈Ço
    ports:
      - "1521:1521"
  frontend:
    build:
      context: ../frontend/
      dockerfile: frontend.Dockerfile
    image: electronmailfrontend
    container_name: em_frontend
    ports:
      - "4200:8080"
volumes:
  em-db-data:
