services:
  db:
    build:
      context: ../database/
      dockerfile: ../database/db.Dockerfile
    image: electronmaildb
    container_name: em_db
    volumes:
      - em-db-data:/opt/oracle

    environment:
      ORACLE_PWD: password #tymczasowe has≈Ço
    ports:
      - "1521:1521"
volumes:
  em-db-data:
