services:
  db:
    build:
      context: ../database/
      dockerfile: db.Dockerfile
    image: electronmaildb
    container_name: em_db
    volumes:
      - em-db-data:/opt/oracle/oradata

    environment:
      ORACLE_PWD: ${DB_SYSTEM_PASSWORD} #tymczasowe has≈Ço

    healthcheck:
      test: [ "CMD", "sh", "-c", "echo 'exit' | sqlplus -L ${DB_USER}/${DB_PASSWORD}@//localhost:${DB_PORT}/${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

    ports:
      - "${DB_PORT}:1521"

  backend:
    build:
      context: ../backend/
      dockerfile: backend.Dockerfile
    image: electronmailbackend
    container_name: em_backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      TFA_AES_KEY: ${TFA_AES_KEY}

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../frontend/
      dockerfile: frontend.Dockerfile
    image: electronmailfrontend
    container_name: em_frontend
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
      BACKEND_HOST: em_backend
      BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:8443"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  em-db-data:
