spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
  session:
    jdbc:
      initialize-schema: never
  jpa:
    hibernate.ddl-auto: none


server:

  servlet:
  
    session.cookie.name: SESSION
    context-path: /api







